server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # React SPA — барлық route index.html-ге
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API сұраулары backend-ке
    location /api/ {
        proxy_pass http://backend:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
