# ============================================================
# Astana Housing — Ansible Inventory
# ============================================================

[local]
localhost ansible_connection=local

[app_servers]
localhost ansible_connection=local

[db_servers]
localhost ansible_connection=local

[monitoring]
localhost ansible_connection=local
